version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: go-book-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./go-book-postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 7s
      timeout: 7s
      retries: 5
    command: [ "postgres", "-c", "log_statement=all" ]
    
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
     - ./books:/apiserver/books
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: